# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: segment_service_input.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='segment_service_input.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bsegment_service_input.proto\"\x8c\x01\n\x15segment_service_input\x12\x10\n\x08\x63lass_id\x18\x01 \x01(\r\x12\'\n\x03img\x18\x02 \x01(\x0b\x32\x1a.segment_service_input.Mat\x1a\x38\n\x03Mat\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x12\n\nimage_data\x18\x03 \x01(\x0c\x62\x06proto3')
)




_SEGMENT_SERVICE_INPUT_MAT = _descriptor.Descriptor(
  name='Mat',
  full_name='segment_service_input.Mat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='segment_service_input.Mat.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='segment_service_input.Mat.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_data', full_name='segment_service_input.Mat.image_data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=172,
)

_SEGMENT_SERVICE_INPUT = _descriptor.Descriptor(
  name='segment_service_input',
  full_name='segment_service_input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='class_id', full_name='segment_service_input.class_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img', full_name='segment_service_input.img', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SEGMENT_SERVICE_INPUT_MAT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=172,
)

_SEGMENT_SERVICE_INPUT_MAT.containing_type = _SEGMENT_SERVICE_INPUT
_SEGMENT_SERVICE_INPUT.fields_by_name['img'].message_type = _SEGMENT_SERVICE_INPUT_MAT
DESCRIPTOR.message_types_by_name['segment_service_input'] = _SEGMENT_SERVICE_INPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

segment_service_input = _reflection.GeneratedProtocolMessageType('segment_service_input', (_message.Message,), dict(

  Mat = _reflection.GeneratedProtocolMessageType('Mat', (_message.Message,), dict(
    DESCRIPTOR = _SEGMENT_SERVICE_INPUT_MAT,
    __module__ = 'segment_service_input_pb2'
    # @@protoc_insertion_point(class_scope:segment_service_input.Mat)
    ))
  ,
  DESCRIPTOR = _SEGMENT_SERVICE_INPUT,
  __module__ = 'segment_service_input_pb2'
  # @@protoc_insertion_point(class_scope:segment_service_input)
  ))
_sym_db.RegisterMessage(segment_service_input)
_sym_db.RegisterMessage(segment_service_input.Mat)


# @@protoc_insertion_point(module_scope)
